---

- hosts: juniper
  tasks:
    - name: show version
      junos_command:
        commands: show version
        format: text
      register: version_output
      

    - name: Extract Hostname and Model
      set_fact:
        hostname: "{{ version_output.stdout_lines[0] | regex_replace('^.*Hostname: (\\S+).*$', '\\1') }}"
        model: "{{ version_output.stdout_lines[0] | regex_replace('^.*Model: (\\S+).*$', '\\1') }}"
        junos: "{{ version_output.stdout_lines[0] | regex_replace('^.*Junos: (\\S+).*$', '\\1') }}"

    - name: Create CSV file and set the header
      lineinfile:
        dest: "DATA/output.csv"
        line:
          Hostname,Model,Junos Version
        create: yes
        state: present
    
    - name: CSV - Write information into .csv file
      lineinfile:
        insertafter: EOF
        dest: "DATA/output.csv"
        line: "{{ hostname | replace(\"'\", '') }}{{ model | replace(\"'\", '') }}{{ junos | replace(\"'\", '') }}"
     


   